/*Iniciando os scripts de DDL */
USE trabalhomdi;

DROP TABLE IF EXISTS PAGAMENTO;
DROP TABLE IF EXISTS RECEBE;
DROP TABLE IF EXISTS EXECUTA;
DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS QUARTO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS GERENTE;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE GERENTE (
    MATRICULA INTEGER PRIMARY KEY,
    DEPARTAMENTO VARCHAR(50),
    SALARIO DECIMAL(12,2)
);

CREATE TABLE FUNCIONARIO (
    MATRICULA INTEGER PRIMARY KEY,
    DEPARTAMENTO VARCHAR(50),
    SALARIO DECIMAL(12,2),
    MATR_GER INTEGER,
    FOREIGN KEY (MATR_GER) REFERENCES GERENTE(MATRICULA)
);

CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(255)
);

CREATE TABLE QUARTO (
    NUMERO INTEGER PRIMARY KEY,
    TIPO VARCHAR(50)
);

CREATE TABLE SERVICO (
    TIPO VARCHAR(50) PRIMARY KEY,
    VALOR DECIMAL(12,2)
);

CREATE TABLE RESERVA (
    ID_RESERVA INTEGER PRIMARY KEY,
    DATA DATETIME,
    CHECKIN DATETIME,
    CHECKOUT DATETIME,
    CPF VARCHAR(11),
    NUMERO_QUARTO INTEGER,
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (NUMERO_QUARTO) REFERENCES QUARTO(NUMERO),
    UNIQUE(DATA, NUMERO_QUARTO, CPF)
);

CREATE TABLE EXECUTA (
    MATRICULA INTEGER,
    TIPO_SERVICO VARCHAR(50),
    PRIMARY KEY (MATRICULA, TIPO_SERVICO),
    FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA),
    FOREIGN KEY (TIPO_SERVICO) REFERENCES SERVICO(TIPO)
);

CREATE TABLE RECEBE (
    ID_RESERVA INTEGER,
    TIPO_SERVICO VARCHAR(50),
    PRIMARY KEY (ID_RESERVA, TIPO_SERVICO),
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
    FOREIGN KEY (TIPO_SERVICO) REFERENCES SERVICO(TIPO)
);

CREATE TABLE PAGAMENTO (
    DATA DATETIME PRIMARY KEY,
    VALOR DECIMAL(12,2),
    FORMA VARCHAR(50),
    ID_RESERVA INTEGER,
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA)
);

