-- Relatório de serviços recebidos num período

SELECT R.ID_RESERVA, R.DATA AS DATA_RESERVA, R.CHECKIN, R.CHECKOUT, C.CPF, C.TELEFONE, REC.TIPO_SERVICO
FROM RECEBE REC
JOIN RESERVA R ON REC.ID_RESERVA = R.ID_RESERVA
JOIN CLIENTE C ON R.CPF = C.CPF
WHERE R.DATA BETWEEN '2025-04-01' AND '2025-05-31'
ORDER BY R.DATA;

-- elatório de receita por mês 

SELECT substr(P.DATA,1,7) AS ANO_MES, COUNT(*) AS NUM_PAGAMENTOS, SUM(P.VALOR) AS TOTAL_RECEITA
FROM PAGAMENTO P
GROUP BY ANO_MES
ORDER BY ANO_MES;

-- Consulta individual (cpf do cliente)

SELECT * FROM CLIENTE WHERE CPF = '11111111111';

-- Consulta individual (detalhes da reserva id da reserva=3)

SELECT R.*, C.TELEFONE, Q.TIPO AS TIPO_QUARTO
FROM RESERVA R
JOIN CLIENTE C ON R.CPF = C.CPF
JOIN QUARTO Q ON R.NUMERO_QUARTO = Q.NUMERO
WHERE R.ID_RESERVA = 3;

-- Consulta de serviços executados por funcionário (matricula=1)

SELECT F.MATRICULA, F.DEPARTAMENTO, E.TIPO_SERVICO, S.VALOR
FROM EXECUTA E
JOIN FUNCIONARIO F ON E.MATRICULA = F.MATRICULA
JOIN SERVICO S ON E.TIPO_SERVICO = S.TIPO
WHERE F.MATRICULA = 1;

-- Consulta de pagamento com info do cliente e do quarto

SELECT P.DATA AS DATA_PAGAMENTO, P.VALOR, P.FORMA, R.ID_RESERVA, R.DATA AS DATA_RESERVA, C.CPF, C.TELEFONE, R.NUMERO_QUARTO
FROM PAGAMENTO P
JOIN RESERVA R ON P.ID_RESERVA = R.ID_RESERVA
JOIN CLIENTE C ON R.CPF = C.CPF
ORDER BY P.DATA;